name: provider_assist
description: Provider Assist gives you a base view and view model which expose information about the system including device information, localization, and errors on top of the provider pattern.
version: 1.1.0
author: Ryan Dixon <ryandixon1993@gmail.com>
homepage: https://github.com/SKLn-Rad/provider_assist

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
