name: provider_assist
description: Wrap provider to expose information about the system including device information, localization, and errors through an MVVM pattern.
version: 2.0.2
homepage: https://github.com/SKLn-Rad/provider_assist

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
