name: provider_assist
description: MVVM state management through provider with a ton of extras on the side to reduce boilerplate in development!
version: 2.0.0
homepage: https://github.com/SKLn-Rad/provider_assist

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
