name: provider_assist
description: Wrap provider to expose information about the system including device information, localization, and errors through an MVVM pattern.
version: 1.3.0
author: Ryan Dixon <ryandixon1993@gmail.com>
homepage: https://github.com/SKLn-Rad/provider_assist

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
